// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKrG63j808eCLU1n0pYknCQssctqoVcxM',
    appId: '1:462435448337:web:319efd6e4b9bd69a6263b0',
    messagingSenderId: '462435448337',
    projectId: 'parkinsons-detection',
    authDomain: 'parkinsons-detection.firebaseapp.com',
    storageBucket: 'parkinsons-detection.firebasestorage.app',
    measurementId: 'G-C02QYWQCRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2z5I1uQGx-p3Unvh7LaNHRBxzhNU5HLg',
    appId: '1:462435448337:android:2f5610f0cd8ecafd6263b0',
    messagingSenderId: '462435448337',
    projectId: 'parkinsons-detection',
    storageBucket: 'parkinsons-detection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMiX6JpWiivf8c0yp9oHWmhbIptxTnViw',
    appId: '1:462435448337:ios:1dcaf8b322539a446263b0',
    messagingSenderId: '462435448337',
    projectId: 'parkinsons-detection',
    storageBucket: 'parkinsons-detection.firebasestorage.app',
    iosBundleId: 'com.example.parkinscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMiX6JpWiivf8c0yp9oHWmhbIptxTnViw',
    appId: '1:462435448337:ios:1dcaf8b322539a446263b0',
    messagingSenderId: '462435448337',
    projectId: 'parkinsons-detection',
    storageBucket: 'parkinsons-detection.firebasestorage.app',
    iosBundleId: 'com.example.parkinscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKrG63j808eCLU1n0pYknCQssctqoVcxM',
    appId: '1:462435448337:web:cc6847a773f81e386263b0',
    messagingSenderId: '462435448337',
    projectId: 'parkinsons-detection',
    authDomain: 'parkinsons-detection.firebaseapp.com',
    storageBucket: 'parkinsons-detection.firebasestorage.app',
    measurementId: 'G-KX9N9FJZMZ',
  );
}
